# Generated by Django 3.0.5 on 2021-04-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tienda',
            new_name='Producto',
        ),
    ]
