# Generated by Django 3.0.5 on 2021-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210408_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='nuevos',
            field=models.BooleanField(default=False),
        ),
    ]
