# Generated by Django 3.0.5 on 2021-04-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_producto_imgpro5'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nuevos',
            field=models.BooleanField(default=False),
        ),
    ]
