# Generated by Django 3.0.5 on 2021-04-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210415_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalogo',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='catalogo',
            new_name='categoria',
        ),
    ]
