# Generated by Django 3.0.5 on 2021-04-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210415_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombreCategoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nombreProducto',
        ),
    ]
