# Generated by Django 3.0.5 on 2021-05-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210430_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='portada',
            field=models.BooleanField(default=False),
        ),
    ]
