# Generated by Django 3.0.5 on 2021-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210527_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tela',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreTela',
            field=models.ManyToManyField(to='app.Tela'),
        ),
    ]
