# Generated by Django 3.0.5 on 2021-05-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210527_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombreTela',
            field=models.ManyToManyField(null=True, to='app.Tela'),
        ),
    ]
